baseURL = "/"
languageCode = "en-us"
title = "My Research Digest"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "papers"
    name = "Papers"
    url = "/paper/"
    weight = 1

  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/video/"
    weight = 2